### ISSUE TITLE
Problem with parseawk

### ISSUE THREAD

**Issue by mladen5000** [microgenomics/pasteTaxID#7]
I am having issues with getting the basic examples of pasteTaxID to work, but if I use a previous version the code works fine. The current version will obtain taxIDs but simply place them in a separate .txt file.

**Comment by Sanrrone** [comment]
Hi mladen5000!, could you give me the file you are using? or a part of it, just for replicate the error you said.
regards.

**Comment by mladen5000** [comment]
My error is generated from the newest version of the bash script, the one that runs successfully is the commit in f10ca7437. I chose this one arbitrarily but it is able to run for the most part.

I say for the most part because I am able to run the f10ca7437 script successfully on my institutions remote cluster as long as I run it directly through the login node, but the script will end up looping indefinitely on a single taxa if I submit it as a remote job submission. I realize this may have more to do with the specifics of my remote environment but figured it's worth mentioning in case you have any additional insight of the discrepancy.

**Comment by Sanrrone** [comment]
That change (`f10ca74`) have no sence in terms of performance because is just readme update change, and it's curious when you said the script is looping indefinitely on a single taxa, so to help you I need three things: 
* the command line have used?
* the file you used (including the taxa that cause the infinite looping) or part of it
* try to run the script using `-- debug` parameter and give me the output in order to understand why you have getting this error.

I'll wait for your answer :+1: 
regards

**Comment by Sanrrone** [comment]
Dear, I already update the repo, try to use the new version, (if you have lot of fastas headers, please create an NCBI api key and use the parallel option), see the Readme for new changes.

regards

**Comment by mladen5000** [comment]
Thank you!
